# Generated by Django 3.0.6 on 2020-05-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
    ]
